# Generated by Django 2.1.7 on 2019-05-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengers',
            options={'verbose_name': 'New Customers', 'verbose_name_plural': 'Customer List for Police Record'},
        ),
    ]
